#!/usr/bin/env zsh
. /home/matthew/.oh-my-zsh/lib/git.zsh # access git shortcuts

echo '>> fetching changes'
git fetch --all && git rebase origin/main --autostash && git push -u -f origin $(git_current_branch)

echo '>>>>>>>> RUNNING SCRAPER >>>>>>>>'
./runner 
